### ISSUE TITLE
Add theme-ui for styling

### ISSUE THREAD

**Issue by raae** [raae/bottledhappiness#1]

**Comment by PaulieScanlon** [comment]
1. `yarn add gatsby-plugin-theme-ui theme-ui`
2. add `gatsby-plugin-theme-ui` to gatsby plugins array in `gatsby-config`

```javascript
module.exports = {
      plugins: ['gatsby-plugin-theme-ui']
    }
```
   3. create a dir with an index.js in `src/gatsby-plugin-theme-ui/index.js`
   4. copy the basic colors object... there's more details in the [docs](https://theme-ui.com/components/button#variants)
```javascript
export default {
   colors: {
       text: '#333333',
       background: '#ffffff',
       primary: '#FF5BA3',
      }
    }
```

5. in your index import a button: `import {Button} from 'theme-ui'`
6. use the button somewhere `<Button>Boogy Time</Button>`
