### ISSUE TITLE
Play sound when bottle is clicked

### ISSUE THREAD

**Issue by raae** [raae/bottledhappiness#3]
I think we should use: https://github.com/joshwcomeau/use-sound

For now play the sound once on click, but then later we want the sound to loop for as long as the user clicks the bottle.

Also, for now the bottle is just a simple button.

**Comment by raae** [comment]
Looks great 🎉 

I think the best ui would be to keep playing (looping) as long as people keep clicking and then stopping when they stop clicking.

This will be very similar to the hover example here: https://github.com/joshwcomeau/use-sound

But you will need to use the onMouseDown and onMouseUp events, instead of Enter/Leave.

Also figure out how to do looping with useSound.

**Comment by raae** [comment]
Also find a better example sound if you want me to merge.

**Comment by olavea** [comment]
```
import React from "react"
import { Button, Flex, Box } from "theme-ui"


import useSound from 'use-sound'

// record Lillian (5.5 🦄) and Liv (7) and add laugh1 in the sounds folder
import laugh1 from '../../sounds/534709__artymarce__childlaugh.mp3';

export default function Home() {
  const [play, {stop}] = useSound(laugh1);
  return (
    <Flex
      bg=""
      sx={{
        height: "100vh",
        width: "100vw",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Box>
        <Button
          onClick={play}
          // What should the user do to stop laughter?
          // Frown? Say "STOP laughing!"
          sx={{ height: "80vh", width: "clamp(30px, 30vw, 600px)" }}
        >
          Bottle placeholder
        </Button>
      </Box>
    </Flex>
  )
}

```
