### ISSUE TITLE
Bug: sound not playing on Nick's iPhone

### ISSUE THREAD

**Issue by olavea** [raae/bottledhappiness#36]
Check Ola's iPad Mini
- [x] Sound is working in Chrome
- [x] Sound is working in Safari
- [x] What iOS? 12.4.7 (so the wrong one if 14 is the problem)

Check Nick's iPhone
- [ ] Sound is not working
- [ ] What browser?
- [ ] What iOS

Check Ola's iPhone
- [x] Start charging battery
- [ ] Sound is working
- [ ] What browser? 
- [ ] Get iOS 14 

Check Ola's Android
- [ ] Sound is working
- [ ] What browser? Safari
- [ ] What iOS 12.4.7 (?)

**Comment by olavea** [comment]
iOS 14 seems to be a problem
https://github.com/4ian/GDevelop/issues/1991

**Comment by raae** [comment]
> iOS 14 seems to be a problem
> [4ian/GDevelop#1991](https://github.com/4ian/GDevelop/issues/1991)

This seems to be an issue with waw, and we are using mp3

**Comment by raae** [comment]
https://twitter.com/NKCSS/status/1345071954252992512?s=19
